fancybox: true ## If you want to use fancybox please set the value to true.
duoshuo: ## Your duoshuo_shortname, e.g. username
disqus: sunqiangsblog ## Your disqus_shortname, e.g. username
google_search: ## Use Google search, true/false.
baidu_search: ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: ## Use a jQuery-based local search engine, true/false.
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: false ## If you want to show the count of categories in the sidebar widget please set the value to true.
shareto: true ## If you want to use the share button please set the value to true.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: diary
    directory: diary/
    icon: fa-heart
  - page: wishlist
    directory: wishlist/
    icon: fa-list-ol
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  - title: 跨界的IT博客
    url: http://www.leocook.org/
  - title: 屠夫9441的博客
    url: https://www.haomwei.com/
  - title: James Pan's Blog
    url: https://blog.jamespan.me/

timeline:
  - num: 1
    word: 2010/09 - 统招进入天津大学计算机科学与技术学院学习
  - num: 2
    word: 2014/06 - 毕业后留在天津，就职于天津华永无线科技有限公司，初级Android研发工程师，主要从事Android界面需求开发
  - num: 3
    word: 2016/03 - 离开天津，开始北漂，就职于魔秀科技（北京）股份有限公司，中级Android研发工程师，主要从事Android基础功能组件开发及插件化、热更新的应用

# Static files
js: js
css: css

# Theme version
version: 0.0.0