fancybox: true ## If you want to use fancybox please set the value to true.
duoshuo: ## Your duoshuo_shortname, e.g. username
disqus: sunqiangsblog ## Your disqus_shortname, e.g. username
uyan: ## Your uyan_id. e.g. 1234567
gentie: ## Your gentie_productKey, e.g. fc799538c7ad4cf5a5a0c2877a90cbd7
changyan: ## Your changyan appid
changyan_conf: ## You changyan conf
google_search: true ## Use Google search, true/false.
baidu_search: ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: ## Use a jQuery-based local search engine, true/false.
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: false ## If you want to show the count of categories in the sidebar widget please set the value to true.
toc_number: true ## If you want to add list number to toc please set the value to true.
shareto: true ## If you want to use the share button please set the value to true.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: diary
    directory: diary/
    icon: fa-heart
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  - title: 跨界的IT博客
    url: http://www.leocook.org/
  - title: 屠夫9441的博客
    url: https://www.haomwei.com/
  - title: James Pan's Blog
    url: https://blog.jamespan.me/

timeline:
  - num: 1
    word: 2010/09 - 统招进入天津大学计算机科学与技术学院学习
  - num: 2
    word: 2014/06 - 就职于天津华永无线科技有限公司，初级Android研发工程师，从事Android线上产品的维护和迭代开发、新项目的探索和实践。
  - num: 3
    word: 2016/03 - 就职于魔秀科技（北京）股份有限公司，中级Android研发工程师，从事过Android基础功能组件开发、插件化，热更新的应用、性能优化、带领新项目并兼Unity开发。

# Static files
js: js
css: css

# Theme version
version: 0.0.0